
package org.nema.dicom.PS3_19;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IHostService-20100825", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825")
@XmlSeeAlso({
    ObjectFactoryHost.class
})
public interface IHostService20100825 {


    /**
     * 
     * @return
     *     returns org.nema.dicom.PS3_19.UID
     */
    @WebMethod(operationName = "GenerateUID", action = "http://dicom.nema.org/PS3.19/IHostService/GenerateUID")
    @WebResult(name = "GenerateUIDResult", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825")
    @RequestWrapper(localName = "GenerateUID", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825", className = "org.nema.dicom.PS3_19.GenerateUID")
    @ResponseWrapper(localName = "GenerateUIDResponse", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825", className = "org.nema.dicom.PS3_19.GenerateUIDResponse")
    public UID generateUID();

    /**
     * 
     * @param preferredScreen
     * @return
     *     returns org.nema.dicom.PS3_19.Rectangle
     */
    @WebMethod(operationName = "GetAvailableScreen", action = "http://dicom.nema.org/PS3.19/IHostService/GetAvailableScreen")
    @WebResult(name = "GetAvailableScreenResult", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825")
    @RequestWrapper(localName = "GetAvailableScreen", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825", className = "org.nema.dicom.PS3_19.GetAvailableScreen")
    @ResponseWrapper(localName = "GetAvailableScreenResponse", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825", className = "org.nema.dicom.PS3_19.GetAvailableScreenResponse")
    public Rectangle getAvailableScreen(
        @WebParam(name = "preferredScreen", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825")
        Rectangle preferredScreen);

    /**
     * 
     * @param preferredProtocols
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetOutputLocation", action = "http://dicom.nema.org/PS3.19/IHostService/GetOutputLocation")
    @WebResult(name = "GetOutputLocationResult", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825")
    @RequestWrapper(localName = "GetOutputLocation", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825", className = "org.nema.dicom.PS3_19.GetOutputLocation")
    @ResponseWrapper(localName = "GetOutputLocationResponse", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825", className = "org.nema.dicom.PS3_19.GetOutputLocationResponse")
    public String getOutputLocation(
        @WebParam(name = "preferredProtocols", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825")
        ArrayOfstring preferredProtocols);

    /**
     * 
     * @param state
     */
    @WebMethod(operationName = "NotifyStateChanged", action = "http://dicom.nema.org/PS3.19/IHostService/NotifyStateChanged")
    @RequestWrapper(localName = "NotifyStateChanged", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825", className = "org.nema.dicom.PS3_19.NotifyStateChanged")
    @ResponseWrapper(localName = "NotifyStateChangedResponse", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825", className = "org.nema.dicom.PS3_19.NotifyStateChangedResponse")
    public void notifyStateChanged(
        @WebParam(name = "state", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825")
        State state);

    /**
     * 
     * @param status
     */
    @WebMethod(operationName = "NotifyStatus", action = "http://dicom.nema.org/PS3.19/IHostService/NotifyStatus")
    @RequestWrapper(localName = "NotifyStatus", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825", className = "org.nema.dicom.PS3_19.NotifyStatus")
    @ResponseWrapper(localName = "NotifyStatusResponse", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825", className = "org.nema.dicom.PS3_19.NotifyStatusResponse")
    public void notifyStatus(
        @WebParam(name = "status", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825")
        Status status);

    /**
     * 
     * @param data
     * @param lastData
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "NotifyDataAvailable", action = "http://dicom.nema.org/PS3.19/IHostService/NotifyDataAvailable")
    @WebResult(name = "NotifyDataAvailableResult", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825")
    @RequestWrapper(localName = "NotifyDataAvailable", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825", className = "org.nema.dicom.PS3_19.NotifyDataAvailable")
    @ResponseWrapper(localName = "NotifyDataAvailableResponse", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825", className = "org.nema.dicom.PS3_19.NotifyDataAvailableResponse")
    public Boolean notifyDataAvailable(
        @WebParam(name = "data", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825")
        AvailableData data,
        @WebParam(name = "lastData", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825")
        Boolean lastData);

    /**
     * 
     * @param acceptableTransferSyntaxes
     * @param includeBulkData
     * @param objects
     * @return
     *     returns org.nema.dicom.PS3_19.ArrayOfObjectLocator
     */
    @WebMethod(operationName = "GetData", action = "http://dicom.nema.org/PS3.19/IHostService/GetData")
    @WebResult(name = "GetDataResult", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825")
    @RequestWrapper(localName = "GetData", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825", className = "org.nema.dicom.PS3_19.GetData")
    @ResponseWrapper(localName = "GetDataResponse", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825", className = "org.nema.dicom.PS3_19.GetDataResponse")
    public ArrayOfObjectLocator getData(
        @WebParam(name = "objects", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825")
        ArrayOfUUID objects,
        @WebParam(name = "acceptableTransferSyntaxes", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825")
        ArrayOfUID acceptableTransferSyntaxes,
        @WebParam(name = "includeBulkData", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825")
        Boolean includeBulkData);

    /**
     * 
     * @param objects
     */
    @WebMethod(operationName = "ReleaseData", action = "http://dicom.nema.org/PS3.19/IHostService/ReleaseData")
    @RequestWrapper(localName = "ReleaseData", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825", className = "org.nema.dicom.PS3_19.ReleaseData")
    @ResponseWrapper(localName = "ReleaseDataResponse", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825", className = "org.nema.dicom.PS3_19.ReleaseDataResponse")
    public void releaseData(
        @WebParam(name = "objects", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825")
        ArrayOfUUID objects);

    /**
     * 
     * @param classUID
     * @param supportedInfoSetTypes
     * @param objects
     * @return
     *     returns org.nema.dicom.PS3_19.ModelSetDescriptor
     */
    @WebMethod(operationName = "GetAsModels", action = "http://dicom.nema.org/PS3.19/IHostService/GetAsModels")
    @WebResult(name = "GetAsModelsResult", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825")
    @RequestWrapper(localName = "GetAsModels", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825", className = "org.nema.dicom.PS3_19.GetAsModels")
    @ResponseWrapper(localName = "GetAsModelsResponse", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825", className = "org.nema.dicom.PS3_19.GetAsModelsResponse")
    public ModelSetDescriptor getAsModels(
        @WebParam(name = "objects", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825")
        ArrayOfUUID objects,
        @WebParam(name = "classUID", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825")
        UID classUID,
        @WebParam(name = "supportedInfoSetTypes", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825")
        ArrayOfMimeType supportedInfoSetTypes);

    /**
     * 
     * @param models
     */
    @WebMethod(operationName = "ReleaseModels", action = "http://dicom.nema.org/PS3.19/IHostService/ReleaseModels")
    @RequestWrapper(localName = "ReleaseModels", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825", className = "org.nema.dicom.PS3_19.ReleaseModels")
    @ResponseWrapper(localName = "ReleaseModelsResponse", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825", className = "org.nema.dicom.PS3_19.ReleaseModelsResponse")
    public void releaseModels(
        @WebParam(name = "models", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825")
        ArrayOfUUID models);

    /**
     * 
     * @param models
     * @param xPaths
     * @return
     *     returns org.nema.dicom.PS3_19.ArrayOfQueryResult
     */
    @WebMethod(operationName = "QueryModel", action = "http://dicom.nema.org/PS3.19/IHostService/QueryModel")
    @WebResult(name = "QueryModelResult", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825")
    @RequestWrapper(localName = "QueryModel", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825", className = "org.nema.dicom.PS3_19.QueryModel")
    @ResponseWrapper(localName = "QueryModelResponse", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825", className = "org.nema.dicom.PS3_19.QueryModelResponse")
    public ArrayOfQueryResult queryModel(
        @WebParam(name = "models", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825")
        ArrayOfUUID models,
        @WebParam(name = "xPaths", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825")
        ArrayOfstring xPaths);

    /**
     * 
     * @param models
     * @param xPaths
     * @return
     *     returns org.nema.dicom.PS3_19.ArrayOfQueryResultInfoSet
     */
    @WebMethod(operationName = "QueryInfoSet", action = "http://dicom.nema.org/PS3.19/IHostService/QueryInfoSet")
    @WebResult(name = "QueryInfoSetResult", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825")
    @RequestWrapper(localName = "QueryInfoSet", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825", className = "org.nema.dicom.PS3_19.QueryInfoSet")
    @ResponseWrapper(localName = "QueryInfoSetResponse", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825", className = "org.nema.dicom.PS3_19.QueryInfoSetResponse")
    public ArrayOfQueryResultInfoSet queryInfoSet(
        @WebParam(name = "models", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825")
        ArrayOfUUID models,
        @WebParam(name = "xPaths", targetNamespace = "http://dicom.nema.org/PS3.19/HostService-20100825")
        ArrayOfstring xPaths);

}
