//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.10.28 at 10:12:54 AM CDT 
//


package gme.cacore_cacore._3_2.edu_northwestern_radiology;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DICOMImageReference complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DICOMImageReference">
 *   &lt;complexContent>
 *     &lt;extension base="{gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIM}ImageReference">
 *       &lt;sequence>
 *         &lt;element name="study">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Study" type="{gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIM}Study"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DICOMImageReference", propOrder = {
    "study"
})
public class DICOMImageReference
    extends ImageReference
{

    @XmlElement(required = true)
    protected DICOMImageReference.Study study;

    /**
     * Gets the value of the study property.
     * 
     * @return
     *     possible object is
     *     {@link DICOMImageReference.Study }
     *     
     */
    public DICOMImageReference.Study getStudy() {
        return study;
    }

    /**
     * Sets the value of the study property.
     * 
     * @param value
     *     allowed object is
     *     {@link DICOMImageReference.Study }
     *     
     */
    public void setStudy(DICOMImageReference.Study value) {
        this.study = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Study" type="{gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIM}Study"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "study"
    })
    public static class Study {

        @XmlElement(name = "Study", required = true)
        protected gme.cacore_cacore._3_2.edu_northwestern_radiology.Study study;

        /**
         * Gets the value of the study property.
         * 
         * @return
         *     possible object is
         *     {@link gme.cacore_cacore._3_2.edu_northwestern_radiology.Study }
         *     
         */
        public gme.cacore_cacore._3_2.edu_northwestern_radiology.Study getStudy() {
            return study;
        }

        /**
         * Sets the value of the study property.
         * 
         * @param value
         *     allowed object is
         *     {@link gme.cacore_cacore._3_2.edu_northwestern_radiology.Study }
         *     
         */
        public void setStudy(gme.cacore_cacore._3_2.edu_northwestern_radiology.Study value) {
            this.study = value;
        }

    }

}
