//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.10.28 at 10:12:54 AM CDT 
//


package gme.cacore_cacore._3_2.edu_northwestern_radiology;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ImageViewModifier complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ImageViewModifier">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="codeSequence">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CodeSequence" type="{gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIM}CodeSequence"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImageViewModifier", propOrder = {
    "codeSequence"
})
public class ImageViewModifier {

    @XmlElement(required = true)
    protected ImageViewModifier.CodeSequence codeSequence;
    @XmlAttribute(required = true)
    protected BigInteger id;

    /**
     * Gets the value of the codeSequence property.
     * 
     * @return
     *     possible object is
     *     {@link ImageViewModifier.CodeSequence }
     *     
     */
    public ImageViewModifier.CodeSequence getCodeSequence() {
        return codeSequence;
    }

    /**
     * Sets the value of the codeSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageViewModifier.CodeSequence }
     *     
     */
    public void setCodeSequence(ImageViewModifier.CodeSequence value) {
        this.codeSequence = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CodeSequence" type="{gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIM}CodeSequence"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "codeSequence"
    })
    public static class CodeSequence {

        @XmlElement(name = "CodeSequence", required = true)
        protected gme.cacore_cacore._3_2.edu_northwestern_radiology.CodeSequence codeSequence;

        /**
         * Gets the value of the codeSequence property.
         * 
         * @return
         *     possible object is
         *     {@link gme.cacore_cacore._3_2.edu_northwestern_radiology.CodeSequence }
         *     
         */
        public gme.cacore_cacore._3_2.edu_northwestern_radiology.CodeSequence getCodeSequence() {
            return codeSequence;
        }

        /**
         * Sets the value of the codeSequence property.
         * 
         * @param value
         *     allowed object is
         *     {@link gme.cacore_cacore._3_2.edu_northwestern_radiology.CodeSequence }
         *     
         */
        public void setCodeSequence(gme.cacore_cacore._3_2.edu_northwestern_radiology.CodeSequence value) {
            this.codeSequence = value;
        }

    }

}
