//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.10.28 at 10:12:54 AM CDT 
//


package gme.cacore_cacore._3_2.edu_northwestern_radiology;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Image complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Image">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="imageView" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ImageView" type="{gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIM}ImageView" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="SOPClassUID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SOPInstanceUID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="imageLaterality" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="patientOrientationRow" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="patientOrientationColumn" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="pixelSpacingHorizontal" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="pixelSpacingVertical" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="acquisitionDatetime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Image", propOrder = {
    "imageView"
})
public class Image {

    protected Image.ImageView imageView;
    @XmlAttribute(required = true)
    protected BigInteger id;
    @XmlAttribute(name = "SOPClassUID", required = true)
    protected String sopClassUID;
    @XmlAttribute(name = "SOPInstanceUID", required = true)
    protected String sopInstanceUID;
    @XmlAttribute
    protected String imageLaterality;
    @XmlAttribute
    protected String patientOrientationRow;
    @XmlAttribute
    protected String patientOrientationColumn;
    @XmlAttribute
    protected Double pixelSpacingHorizontal;
    @XmlAttribute
    protected Double pixelSpacingVertical;
    @XmlAttribute
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar acquisitionDatetime;

    /**
     * Gets the value of the imageView property.
     * 
     * @return
     *     possible object is
     *     {@link Image.ImageView }
     *     
     */
    public Image.ImageView getImageView() {
        return imageView;
    }

    /**
     * Sets the value of the imageView property.
     * 
     * @param value
     *     allowed object is
     *     {@link Image.ImageView }
     *     
     */
    public void setImageView(Image.ImageView value) {
        this.imageView = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the sopClassUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSOPClassUID() {
        return sopClassUID;
    }

    /**
     * Sets the value of the sopClassUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSOPClassUID(String value) {
        this.sopClassUID = value;
    }

    /**
     * Gets the value of the sopInstanceUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSOPInstanceUID() {
        return sopInstanceUID;
    }

    /**
     * Sets the value of the sopInstanceUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSOPInstanceUID(String value) {
        this.sopInstanceUID = value;
    }

    /**
     * Gets the value of the imageLaterality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImageLaterality() {
        return imageLaterality;
    }

    /**
     * Sets the value of the imageLaterality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageLaterality(String value) {
        this.imageLaterality = value;
    }

    /**
     * Gets the value of the patientOrientationRow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientOrientationRow() {
        return patientOrientationRow;
    }

    /**
     * Sets the value of the patientOrientationRow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientOrientationRow(String value) {
        this.patientOrientationRow = value;
    }

    /**
     * Gets the value of the patientOrientationColumn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientOrientationColumn() {
        return patientOrientationColumn;
    }

    /**
     * Sets the value of the patientOrientationColumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientOrientationColumn(String value) {
        this.patientOrientationColumn = value;
    }

    /**
     * Gets the value of the pixelSpacingHorizontal property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPixelSpacingHorizontal() {
        return pixelSpacingHorizontal;
    }

    /**
     * Sets the value of the pixelSpacingHorizontal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPixelSpacingHorizontal(Double value) {
        this.pixelSpacingHorizontal = value;
    }

    /**
     * Gets the value of the pixelSpacingVertical property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPixelSpacingVertical() {
        return pixelSpacingVertical;
    }

    /**
     * Sets the value of the pixelSpacingVertical property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPixelSpacingVertical(Double value) {
        this.pixelSpacingVertical = value;
    }

    /**
     * Gets the value of the acquisitionDatetime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAcquisitionDatetime() {
        return acquisitionDatetime;
    }

    /**
     * Sets the value of the acquisitionDatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAcquisitionDatetime(XMLGregorianCalendar value) {
        this.acquisitionDatetime = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ImageView" type="{gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIM}ImageView" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "imageView"
    })
    public static class ImageView {

        @XmlElement(name = "ImageView")
        protected gme.cacore_cacore._3_2.edu_northwestern_radiology.ImageView imageView;

        /**
         * Gets the value of the imageView property.
         * 
         * @return
         *     possible object is
         *     {@link gme.cacore_cacore._3_2.edu_northwestern_radiology.ImageView }
         *     
         */
        public gme.cacore_cacore._3_2.edu_northwestern_radiology.ImageView getImageView() {
            return imageView;
        }

        /**
         * Sets the value of the imageView property.
         * 
         * @param value
         *     allowed object is
         *     {@link gme.cacore_cacore._3_2.edu_northwestern_radiology.ImageView }
         *     
         */
        public void setImageView(gme.cacore_cacore._3_2.edu_northwestern_radiology.ImageView value) {
            this.imageView = value;
        }

    }

}
