//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.10.28 at 10:12:54 AM CDT 
//


package gme.cacore_cacore._3_2.edu_northwestern_radiology;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ImagingObservation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ImagingObservation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="imagingObservationCharacteristicCollection" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ImagingObservationCharacteristic" type="{gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIM}ImagingObservationCharacteristic" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="relatedImagingObservation" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ImagingObservation" type="{gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIM}ImagingObservation" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="codeMeaning" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="codingSchemeDesignator" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="codeValue" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="comment" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImagingObservation", propOrder = {
    "imagingObservationCharacteristicCollection",
    "relatedImagingObservation"
})
public class ImagingObservation {

    protected ImagingObservation.ImagingObservationCharacteristicCollection imagingObservationCharacteristicCollection;
    protected ImagingObservation.RelatedImagingObservation relatedImagingObservation;
    @XmlAttribute(required = true)
    protected BigInteger id;
    @XmlAttribute(required = true)
    protected String codeMeaning;
    @XmlAttribute(required = true)
    protected String codingSchemeDesignator;
    @XmlAttribute(required = true)
    protected String codeValue;
    @XmlAttribute
    protected String comment;

    /**
     * Gets the value of the imagingObservationCharacteristicCollection property.
     * 
     * @return
     *     possible object is
     *     {@link ImagingObservation.ImagingObservationCharacteristicCollection }
     *     
     */
    public ImagingObservation.ImagingObservationCharacteristicCollection getImagingObservationCharacteristicCollection() {
        return imagingObservationCharacteristicCollection;
    }

    /**
     * Sets the value of the imagingObservationCharacteristicCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImagingObservation.ImagingObservationCharacteristicCollection }
     *     
     */
    public void setImagingObservationCharacteristicCollection(ImagingObservation.ImagingObservationCharacteristicCollection value) {
        this.imagingObservationCharacteristicCollection = value;
    }

    /**
     * Gets the value of the relatedImagingObservation property.
     * 
     * @return
     *     possible object is
     *     {@link ImagingObservation.RelatedImagingObservation }
     *     
     */
    public ImagingObservation.RelatedImagingObservation getRelatedImagingObservation() {
        return relatedImagingObservation;
    }

    /**
     * Sets the value of the relatedImagingObservation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImagingObservation.RelatedImagingObservation }
     *     
     */
    public void setRelatedImagingObservation(ImagingObservation.RelatedImagingObservation value) {
        this.relatedImagingObservation = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the codeMeaning property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeMeaning() {
        return codeMeaning;
    }

    /**
     * Sets the value of the codeMeaning property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeMeaning(String value) {
        this.codeMeaning = value;
    }

    /**
     * Gets the value of the codingSchemeDesignator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodingSchemeDesignator() {
        return codingSchemeDesignator;
    }

    /**
     * Sets the value of the codingSchemeDesignator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodingSchemeDesignator(String value) {
        this.codingSchemeDesignator = value;
    }

    /**
     * Gets the value of the codeValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeValue() {
        return codeValue;
    }

    /**
     * Sets the value of the codeValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeValue(String value) {
        this.codeValue = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ImagingObservationCharacteristic" type="{gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIM}ImagingObservationCharacteristic" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "imagingObservationCharacteristic"
    })
    public static class ImagingObservationCharacteristicCollection {

        @XmlElement(name = "ImagingObservationCharacteristic")
        protected List<ImagingObservationCharacteristic> imagingObservationCharacteristic;

        /**
         * Gets the value of the imagingObservationCharacteristic property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the imagingObservationCharacteristic property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getImagingObservationCharacteristic().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ImagingObservationCharacteristic }
         * 
         * 
         */
        public List<ImagingObservationCharacteristic> getImagingObservationCharacteristic() {
            if (imagingObservationCharacteristic == null) {
                imagingObservationCharacteristic = new ArrayList<ImagingObservationCharacteristic>();
            }
            return this.imagingObservationCharacteristic;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ImagingObservation" type="{gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIM}ImagingObservation" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "imagingObservation"
    })
    public static class RelatedImagingObservation {

        @XmlElement(name = "ImagingObservation")
        protected ImagingObservation imagingObservation;

        /**
         * Gets the value of the imagingObservation property.
         * 
         * @return
         *     possible object is
         *     {@link ImagingObservation }
         *     
         */
        public ImagingObservation getImagingObservation() {
            return imagingObservation;
        }

        /**
         * Sets the value of the imagingObservation property.
         * 
         * @param value
         *     allowed object is
         *     {@link ImagingObservation }
         *     
         */
        public void setImagingObservation(ImagingObservation value) {
            this.imagingObservation = value;
        }

    }

}
