//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.10.28 at 10:12:54 AM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIM", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package gme.cacore_cacore._3_2.edu_northwestern_radiology;
