//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.10.28 at 10:12:54 AM CDT 
//


package gme.cacore_cacore._3_2.edu_northwestern_radiology;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProbabilityMap complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProbabilityMap">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="imagingObservation">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ImagingObservation" type="{gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIM}ImagingObservation"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="instatnceUID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="referencedInstanceUID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProbabilityMap", propOrder = {
    "imagingObservation"
})
public class ProbabilityMap {

    @XmlElement(required = true)
    protected ProbabilityMap.ImagingObservation imagingObservation;
    @XmlAttribute(required = true)
    protected BigInteger id;
    @XmlAttribute(required = true)
    protected String instatnceUID;
    @XmlAttribute(required = true)
    protected String referencedInstanceUID;

    /**
     * Gets the value of the imagingObservation property.
     * 
     * @return
     *     possible object is
     *     {@link ProbabilityMap.ImagingObservation }
     *     
     */
    public ProbabilityMap.ImagingObservation getImagingObservation() {
        return imagingObservation;
    }

    /**
     * Sets the value of the imagingObservation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProbabilityMap.ImagingObservation }
     *     
     */
    public void setImagingObservation(ProbabilityMap.ImagingObservation value) {
        this.imagingObservation = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the instatnceUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstatnceUID() {
        return instatnceUID;
    }

    /**
     * Sets the value of the instatnceUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstatnceUID(String value) {
        this.instatnceUID = value;
    }

    /**
     * Gets the value of the referencedInstanceUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferencedInstanceUID() {
        return referencedInstanceUID;
    }

    /**
     * Sets the value of the referencedInstanceUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferencedInstanceUID(String value) {
        this.referencedInstanceUID = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ImagingObservation" type="{gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIM}ImagingObservation"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "imagingObservation"
    })
    public static class ImagingObservation {

        @XmlElement(name = "ImagingObservation", required = true)
        protected gme.cacore_cacore._3_2.edu_northwestern_radiology.ImagingObservation imagingObservation;

        /**
         * Gets the value of the imagingObservation property.
         * 
         * @return
         *     possible object is
         *     {@link gme.cacore_cacore._3_2.edu_northwestern_radiology.ImagingObservation }
         *     
         */
        public gme.cacore_cacore._3_2.edu_northwestern_radiology.ImagingObservation getImagingObservation() {
            return imagingObservation;
        }

        /**
         * Sets the value of the imagingObservation property.
         * 
         * @param value
         *     allowed object is
         *     {@link gme.cacore_cacore._3_2.edu_northwestern_radiology.ImagingObservation }
         *     
         */
        public void setImagingObservation(gme.cacore_cacore._3_2.edu_northwestern_radiology.ImagingObservation value) {
            this.imagingObservation = value;
        }

    }

}
