//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.10.28 at 10:12:54 AM CDT 
//


package gme.cacore_cacore._3_2.edu_northwestern_radiology;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TwoDSpatialCoordinate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TwoDSpatialCoordinate">
 *   &lt;complexContent>
 *     &lt;extension base="{gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIM}SpatialCoordinate">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="imageReferenceUID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="referencedFrameNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="x" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="y" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TwoDSpatialCoordinate")
public class TwoDSpatialCoordinate
    extends SpatialCoordinate
{

    @XmlAttribute(required = true)
    protected String imageReferenceUID;
    @XmlAttribute(required = true)
    protected BigInteger referencedFrameNumber;
    @XmlAttribute(required = true)
    protected double x;
    @XmlAttribute(required = true)
    protected double y;

    /**
     * Gets the value of the imageReferenceUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImageReferenceUID() {
        return imageReferenceUID;
    }

    /**
     * Sets the value of the imageReferenceUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageReferenceUID(String value) {
        this.imageReferenceUID = value;
    }

    /**
     * Gets the value of the referencedFrameNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getReferencedFrameNumber() {
        return referencedFrameNumber;
    }

    /**
     * Sets the value of the referencedFrameNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setReferencedFrameNumber(BigInteger value) {
        this.referencedFrameNumber = value;
    }

    /**
     * Gets the value of the x property.
     * 
     */
    public double getX() {
        return x;
    }

    /**
     * Sets the value of the x property.
     * 
     */
    public void setX(double value) {
        this.x = value;
    }

    /**
     * Gets the value of the y property.
     * 
     */
    public double getY() {
        return y;
    }

    /**
     * Sets the value of the y property.
     * 
     */
    public void setY(double value) {
        this.y = value;
    }

}
